Sanitize user input removing all line breaks and whitespaces
It also fixes the following error when running the Typescript compiler:
error TS6082: Only 'amd' and 'system' modules are supported alongside --out.

There is no bundle format for CommonJS, so it was replaced by System module
format.